### PR TITLE
adding a simple wrapper script

### PR DESCRIPTION
**Pull request by arschles**
so you don't have to remember the docker commands

### CODE REVIEW

**Comment by treeder** [comment]
Should add some info on how to alias this or something: http://unix.stackexchange.com/questions/146419/creating-an-alias-for-a-bash-script

Be nice to run something like `dgo vendor`, `dgo build`, etc.

**Comment by arschles** [comment]
@treeder done. hopefully they're clear

**Comment by ohohoreilly** [comment]
+1 this is awesome thanks @treeder and @arschles keep up the great work!

**Comment by treeder** [comment]
Sweet, thanks @arschles

**Comment by arschles** [comment]
:+1:

**Pull request merged**
